version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-user
    image: service-user
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - db
    restart: always
    networks:
      - serviceUserNetwork
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"

  db:
    image: postgres
    container_name: service-user-database
    environment:
      - ./config_user/.env
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - serviceUserNetwork

networks:
  serviceUserNetwork:

volumes:
  user_data: